apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slackbot-worker
  labels:
    app: slackbot
    tier: worker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: slackbot
        tier: worker
    spec:
      containers:
      - name: slackbot-app
        image: us.gcr.io/bookun-221813/slackbot:latest
        #command: ["slackbot"]
        ports:
        - name: http-server
          containerPort: 3030
