---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11.4

inputs:
  - name: repo

outputs:
  - name: out

run:
  path: ci/tasks/gen-manifest.yml
  dir: repo
