apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackbot-worker
  labels:
    app: slackbot
    tier: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slackbot
        tier: worker
    spec:
      containers:
      - name: slackbot-app
        image: cappyzawa/slackbot:latest
        env:
        - name: SLACKWEBHOOK
          valueFrom:
            configMapKeyRef:
              key: slack-webhook
              name: slackbot
        - name: CHANNEL
          valueFrom:
            configMapKeyRef:
              key: slack-channel
              name: slackbot
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              key: slack-token
              name: slackbot
        ports:
        - name: http-server
          containerPort: 3030
        - name: debug-port
          containerPort: 6060
  selector:
    matchLabels:
      app: slackbot
      tier: worker
        
