apiVersion: v1
kind: Service
metadata:
  name: slackbot-worker
  labels:
    app: slackbot
    tier: worker
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.157.139
  ports:
  - port: 80
    targetPort: http-server
    name: http-server
  - port: 6060
    targetPort: debug-port
    name: debug-port
  selector:
    app: slackbot
    tier: worker
